export const cardData = [
  {
    id: 1,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How To Unlock OPPO 5G CPE T1a (CTC03)",
    description: "Step-by-step guide to unlock the OPPO 5G CPE T1a router for networks like Zain.",
    image: "https://img.youtube.com/vi/ZfB4KDu994A/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [
      { title: "Model Covered", text: "This video focuses on OPPO 5G CPE T1a (CTC03) router unlocking." },
      { title: "Carrier Unlock", text: "Unlocking is demonstrated for Zain and other supported networks." },
    ],
    video: { title: "OPPO 5G CPE T1a Unlock Guide", url: "https://www.youtube.com/embed/ZfB4KDu994A" },
  },
  {
    id: 2,
    tag: "Technology",
    tagColor: "tag-blue",
    title: "How To Unlock Huawei 5G CPE PRO 2 H122-373",
    description: "Unlock your Huawei 5G CPE Pro 2 router for global carrier support.",
    image: "https://img.youtube.com/vi/6DbACIRlcvY/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [
      { title: "Model Covered", text: "Huawei 5G CPE Pro 2 (H122-373) full unlocking process." },
      { title: "Network Compatibility", text: "Supports unlocking for use with Saudi, UAE, and other carriers." },
    ],
    video: { title: "Huawei 5G CPE Pro 2 Unlock Tutorial", url: "https://www.youtube.com/embed/6DbACIRlcvY" },
  },
  {
    id: 3,
    tag: "Technology",
    tagColor: "tag-orange",
    title: "How to Unlock Zain Brovi CPE 5 H155-381",
    description: "Learn how to unlock the BROVI 5G CPE 5 router model H155-381 for any carrier.",
    image: "https://img.youtube.com/vi/OC_RctGH6Ng/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [
      { title: "Device Info", text: "Step-by-step guide for the H155-381 model from BROVI." },
      { title: "Unlock Benefits", text: "Use your router with any SIM card across multiple countries." },
    ],
    video: { title: "BROVI CPE H155-381 Unlocking Process", url: "https://www.youtube.com/embed/OC_RctGH6Ng" },
  },
  {
    id: 4,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How To Unlock Zain E6878-370 OR STC Huawei 5G E6878-380",
    description: "Complete guide to unlocking Huawei 5G E6878-370 for cross-country carrier use.",
    image: "https://img.youtube.com/vi/24Dsr9K9W3g/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [
      { title: "Model Covered", text: "Huawei 5G E6878-370 router unlocking process." },
      { title: "Global Use", text: "Works across Saudi, Bahrain, Kuwait networks." },
    ],
    video: { title: "Huawei 5G E6878-370 Unlock Guide", url: "https://www.youtube.com/embed/24Dsr9K9W3g" },
  },
  {
    id: 5,
    tag: "Technology",
    tagColor: "tag-green",
    title: "How To Unlock GreenPacket D5H-EA20 OR D5H-EA60",
    description: "Step-by-step unlock tutorial for a 5G CPE router.",
    image: "https://img.youtube.com/vi/xIecRa3ZLTM/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Quick Unlock", text: "Fast unlock process for your 5G router." }],
    video: { title: "5G Router Unlock Guide", url: "https://www.youtube.com/embed/xIecRa3ZLTM" },
  },
  {
    id: 6,
    tag: "Technology",
    tagColor: "tag-blue",
    title: "How To Unlock Huawei 5G CPE PRO H112-370",
    description: "Unlock tutorial for another 5G router model.",
    image: "https://img.youtube.com/vi/LGxFg8oH8r0/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Model Specific", text: "Designed for a specific 5G CPE model." }],
    video: { title: "5G Router Unlock Tutorial 2", url: "https://www.youtube.com/embed/LGxFg8oH8r0" },
  },
  {
    id: 7,
    tag: "Technology",
    tagColor: "tag-orange",
    title: "How to Unlock GHTelcom 5G CPE 3 H138-380 Pro3",
    description: "Unlock your 5G router quickly and easily.",
    image: "https://img.youtube.com/vi/atRy1pdg2PQ/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Easy Steps", text: "Simple dashboard unlock walkthrough." }],
    video: { title: "5G CPE Unlock Video", url: "https://www.youtube.com/embed/atRy1pdg2PQ" },
  },
  {
    id: 8,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How to Unlock Zain OPPO 5G CPE T2",
    description: "Carrier-friendly unlock tutorial for 5G CPE.",
    image: "https://img.youtube.com/vi/RVYJIteOq1A/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Carrier Support", text: "Works with multiple Middle Eastern carriers." }],
    video: { title: "5G CPE Carrier Unlock", url: "https://www.youtube.com/embed/RVYJIteOq1A" },
  },
  {
    id: 9,
    tag: "Technology",
    tagColor: "tag-green",
    title: "How to Unlock Brovi CPE 5 H155-382",
    description: "Guide for unlocking another model of 5G expansion router.",
    image: "https://img.youtube.com/vi/gIo6TAtgIQk/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Unlocking Steps", text: "Dives into firmware configuration and unlock codes." }],
    video: { title: "5G CPE Unlock Walkthrough", url: "https://www.youtube.com/embed/gIo6TAtgIQk" },
  },
  {
    id: 10,
    tag: "Technology",
    tagColor: "tag-blue",
    title: "How to Unlock Soyealink SRT875 OR SRT873",
    description: "Another 5G CPE unlock demonstration with tips.",
    image: "https://img.youtube.com/vi/KRJXtEQIQgc/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Quick Guide", text: "Fast unlock steps, no software necessary." }],
    video: { title: "5G CPE Unlock Guide 3", url: "https://www.youtube.com/embed/KRJXtEQIQgc" },
  },
  {
    id: 11,
    tag: "Technology",
    tagColor: "tag-orange",
    title: "How to Unlock THREE Brovi CPE 5 H155-381 UK",
    description: "In-depth guide for unlocking 5G CPE system.",
    image: "https://img.youtube.com/vi/jj7wxiHNv_4/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Deep Dive", text: "Explores advanced unlock parameters." }],
    video: { title: "5G CPE Unlock Deep Dive", url: "https://www.youtube.com/embed/jj7wxiHNv_4" },
  },
  {
    id: 12,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How to Unlock Brovi CPE 5 H155-383",
    description: "Unlock tutorial targeting firmware-based locks.",
    image: "https://img.youtube.com/vi/ixoOb8giatE/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Firmware Focus", text: "Tutorial covers firmware unlock module." }],
    video: { title: "5G CPE Firmware Unlock", url: "https://www.youtube.com/embed/ixoOb8giatE" },
  },
  {
    id: 13,
    tag: "Technology",
    tagColor: "tag-green",
    title: "How to Unlock Brovi CPE 5 5G H155-381 Kuwait",
    description: "Carrier-neutral guide for unlocking 5G routers.",
    image: "https://img.youtube.com/vi/cDySfiW-5Rc/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Neutral Unlock", text: "Applies to routers in many regions." }],
    video: { title: "5G Router Universal Unlock", url: "https://www.youtube.com/embed/cDySfiW-5Rc" },
  },
  {
    id: 14,
    tag: "Technology",
    tagColor: "tag-blue",
    title: "How to Unlock Zain Greenpaket E5-250MK",
    description: "Unlock guide tailored for Middle East carriers.",
    image: "https://img.youtube.com/vi/74qreSTmv9o/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Regional Focus", text: "Targeted at Saudi, Bahrain, Kuwait unlocks." }],
    video: { title: "5G Router ME Unlock", url: "https://www.youtube.com/embed/74qreSTmv9o" },
  },
  {
    id: 15,
    tag: "Technology",
    tagColor: "tag-orange",
    title: "ZTE 5G MC801A OR ZTE 5G MC801A1 Unlock",
    description: "Tutorial for unlocking Next-gen 5G CPE devices.",
    image: "https://img.youtube.com/vi/VbZHkXZmUEA/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Next-gen Model", text: "Covers unlocking of a newer 5G CPE model." }],
    video: { title: "5G Next-gen Router Unlock", url: "https://www.youtube.com/embed/VbZHkXZmUEA" },
  },
  {
    id: 16,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How to Mobily 5G Brovi CPE-5 H155-381",
    description: "Final video unlocking a premium 5G CPE router.",
    image: "https://img.youtube.com/vi/i9o5izDktSQ/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "Premium Model", text: "Detailed unlock of a high-end CPE router." }],
    video: { title: "5G Premium Router Unlock", url: "https://www.youtube.com/embed/i9o5izDktSQ" },
  },
  {
    id: 17,
    tag: "Technology",
    tagColor: "tag-teal",
    title: "How To Unlock AirBox 5G EMTEL H155-381.",
    description: "Final video unlocking AirBox 5G EMTEL H155-381",
    image: "https://img.youtube.com/vi/6pweg6d09bI/maxresdefault.jpg",
    user: {
      name: "Genuine Unlocker",
      time: "Just now",
      image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
    },
    content: [{ title: "AirBox 5G EMTEL H155-381", text: "Detailed unlock of a high-end CPE router." }],
    video: { title: "AirBox 5G  EMTEL H155-381 Router Unlock", url: "https://www.youtube.com/embed/6pweg6d09bI" },
  },
  {
  id: 18,
  tag: "Technology",
  tagColor: "tag-teal",
  title: "How To Unlock STC 5G Brovi CPE Pro 5 H158-381.",
  description: "Step-by-step video unlocking STC 5G Brovi CPE Pro 5 H158-381.",
  image: "https://img.youtube.com/vi/6pZKZ5auFTA/maxresdefault.jpg",
  user: {
    name: "Genuine Unlocker",
    time: "Just now",
    image: "https://yt3.ggpht.com/ytc/AGIKgqP0Aq0XzZc5xL9Qk1Ffd7IExZ7Crw9JHcZn7g=s88-c-k-c0x00ffffff-no-rj",
  },
  content: [
    { 
      title: "STC 5G Brovi CPE Pro 5 H158-381", 
      text: "Detailed unlock guide for STC 5G Brovi CPE Pro 5 router." 
    }
  ],
  video: { 
    title: "STC 5G Brovi CPE Pro 5 H158-381 Unlocking", 
    url: "https://www.youtube.com/embed/6pZKZ5auFTA" 
  },
}

];
